In [2]:
import numpy as np

In [ ]:
ar = np.array([1,12,2,3,3])

In [ ]:
ar

In [ ]:
print(ar)

In [ ]:
ar[2] = 10
print(ar)

In [ ]:
a_mul = np.array([[1,2,3,],
                  [4,5,6],
                  [7,8,9]])

print(a_mul[0])
print([a_mul[2,2]])

In [ ]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d)

In [ ]:
print(d.shape)

In [ ]:
print(d.ndim)

In [ ]:
print(d.size)

In [ ]:
print(d.dtype)

In [ ]:
g = np.full((2,3,5),9)
print(g)

x_value = np.arange(0,1005,5)
print(x_value)

In [ ]:
x_values = np.linspace(0,1000,1001)
print(x_values)

In [ ]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]

a1 = np.array(l1)
a2 = np.array(l2)

print(a1 * a2)
print(l1 * 5)
print(a1 - a2)

In [ ]:
a = np.array([1,2,3,4])

ar = np.append(a,[6,7,8,9])
print(ar)

In [ ]:

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

In [ ]:
z = np.array([1,2,3,4,5])
l = np.array([6,7,8,9,10])
n = np.append(a,l)
print(n)

In [ ]:
g = np.array([1,2,3])

b = np.append(g,[7,8,9])
j = np.insert(b,3,[4,5,6])
print(j)

In [ ]:
j = np.array([[1,2,3],
              [6,7,8]])
m = np.delete(j,0,1)
print(m)

In [4]:
p = np.array([[1, 2, 3, 4], 
              [4, 5, 6, 7],
              [8, 9, 10,11],
              [12, 13, 14, 15]])

print(p.shape)
print(p.reshape(8, 2))
print(p.resize(2,2))
print(p.flatten())
print(p.ravel())
print(p.T)
print(p.swapaxes(0,1))

(4, 4)
[[ 1  2]
 [ 3  4]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
None
[1 2 3 4]
[1 2 3 4]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [9]:
a1 = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
a2 = np.array([[11,12,13,14,15],
              [16,17,18,19,20]])
p = np.concatenate((a1,a2),axis=1)
print(p)
u = np.stack((a1,a2))
print(u)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [16]:
a1 = np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20]])
m = np.split(a1,4,axis=0)
print(m)

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20]])]


In [19]:
a1 = np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20]])
print(a1.min())
print(a1.max())
print(a1.std())
print(a1.mean())
print(a1.sum())
print(np.median(a1))

1
20
5.766281297335398
10.5
210
10.5


In [23]:
numbers = np.random.randint(100,size=(2,3,5))
print(numbers)

[[[37 99 69 85  4]
  [94 44 78 52 41]
  [65 23 33 63 34]]

 [[63 83 48 18 41]
  [59 94 57 99 54]
  [81 40 35 47 29]]]


In [24]:
numbers = np.random.binomial(10, p=0.5,size=(2,3))
print(numbers)

[[3 7 6]
 [3 5 8]]


In [25]:
numbers = np.random.normal(loc=10,scale=15,size=(2,5))
print(numbers)

[[ 29.98017061  18.55629069  47.19054932  29.65174115  -6.97195496]
 [  1.67436353  26.76504547  27.65958357  12.57863415 -27.24383886]]


In [27]:
numbers = np.random.choice([1,2,3,4,5], size=(2,3))
print(numbers)

[[5 3 1]
 [5 2 1]]
